// <auto-generated />
using System;
using GenXThofa.Technologies.Estimer.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenXThofa.Technologies.Estimer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ActionType", b =>
                {
                    b.Property<int>("ActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ActionTypeId");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyContactPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ClientAuditLog", b =>
                {
                    b.Property<int>("ClientAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClientAuditLogId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("ClientAuditLogs");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.CostType", b =>
                {
                    b.Property<int>("CostTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CostTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresMonths")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresQuantity")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresRate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CostTypeId");

                    b.ToTable("CostTypes");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EntityType", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EntityTypeId");

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Estimate", b =>
                {
                    b.Property<int>("EstimateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientRemarks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("EstimationStatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ProfitAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ProfitPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("TaxId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalAdditionalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalDirectCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalIndirectCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("VersionNumber")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("EstimateId");

                    b.HasIndex("EstimationStatusId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaxId");

                    b.ToTable("Estimates");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateAdditionalCost", b =>
                {
                    b.Property<int>("EstimateAdditionalCostId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CostTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EstimateAdditionalCostId");

                    b.HasIndex("CostTypeId");

                    b.ToTable("EstimateAdditionalCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateDirectCost", b =>
                {
                    b.Property<int>("EstimateDirectCostId")
                        .HasColumnType("int");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CostTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimationId")
                        .HasColumnType("int");

                    b.Property<int?>("MonthsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("QuantityOrHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("RateOrCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EstimateDirectCostId");

                    b.HasIndex("CostTypeId");

                    b.ToTable("EstimateDirectCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateIndirectCost", b =>
                {
                    b.Property<int>("EstimateIndirectCostId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CostName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CostTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstimationId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EstimateIndirectCostId");

                    b.HasIndex("CostTypeId");

                    b.ToTable("EstimateIndirectCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateLaborCost", b =>
                {
                    b.Property<int>("EstimateLaborCostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("EstimationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EstimateLaborCostId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EstimateLaborCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimationStatus", b =>
                {
                    b.Property<int>("EstimationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EstimationStatusId");

                    b.ToTable("EstimationStatuses");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("AdvancePercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("BalanceDue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ClientId");

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.InvoiceAuditLog", b =>
                {
                    b.Property<int>("InvoiceAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InvoiceAuditLogId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("InvoiceAuditLogs");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.InvoiceStatus", b =>
                {
                    b.Property<int>("InvoiceStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InvoiceStatusId");

                    b.ToTable("InvoiceStatuses");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.MilestoneStatus", b =>
                {
                    b.Property<int>("MilestoneStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MilestoneStatusId");

                    b.ToTable("MilestoneStatuses");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentMode", b =>
                {
                    b.Property<int>("PaymentModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaymentModeId");

                    b.ToTable("PaymentModes");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentReceipt", b =>
                {
                    b.Property<int>("PaymentReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentModeId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("PaymentReceiptId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentModeId");

                    b.ToTable("PaymentReceipts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalBillingAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("PaymentTerms")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProjectManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectManagerId");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectAuditLog", b =>
                {
                    b.Property<int>("ProjectAuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectAuditLogId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("ProjectAuditLogs");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectMilestone", b =>
                {
                    b.Property<int>("ProjectMilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MilestoneAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MilestoneName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MilestoneStatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PaymentPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProjectMilestoneId");

                    b.HasIndex("MilestoneStatusId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMilestones");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectStatus", b =>
                {
                    b.Property<int>("ProjectStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StatusColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProjectStatusId");

                    b.ToTable("ProjectStatuses");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectTeamMember", b =>
                {
                    b.Property<int>("ProjectTeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamRoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ProjectTeamMemberId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RolesRoleId");

                    b.HasIndex("TeamRoleId");

                    b.ToTable("ProjectTeamMembers");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.TaxConfig", b =>
                {
                    b.Property<int>("TaxConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TaxConfigId");

                    b.ToTable("TaxConfigs");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.TeamRole", b =>
                {
                    b.Property<int>("TeamRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("TeamRoleId");

                    b.ToTable("TeamRoles");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Client", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "CreatedByUser")
                        .WithMany("CreatedClients")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "UpdatedByUser")
                        .WithMany("UpdatedClients")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ClientAuditLog", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionType");

                    b.Navigation("EntityType");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Estimate", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.EstimationStatus", "EstimationStatus")
                        .WithMany("Estimates")
                        .HasForeignKey("EstimationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Project", "Project")
                        .WithMany("Estimates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.TaxConfig", "Tax")
                        .WithMany("Estimates")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstimationStatus");

                    b.Navigation("Project");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateAdditionalCost", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.CostType", "CostType")
                        .WithMany("AdditionalCosts")
                        .HasForeignKey("CostTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Estimate", "Estimation")
                        .WithMany("AdditionalCosts")
                        .HasForeignKey("EstimateAdditionalCostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostType");

                    b.Navigation("Estimation");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateDirectCost", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.CostType", "CostType")
                        .WithMany("DirectCosts")
                        .HasForeignKey("CostTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Estimate", "Estimation")
                        .WithMany("DirectCosts")
                        .HasForeignKey("EstimateDirectCostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostType");

                    b.Navigation("Estimation");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateIndirectCost", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.CostType", "CostType")
                        .WithMany("IndirectCosts")
                        .HasForeignKey("CostTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Estimate", "Estimation")
                        .WithMany("IndirectCosts")
                        .HasForeignKey("EstimateIndirectCostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostType");

                    b.Navigation("Estimation");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimateLaborCost", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "Employee")
                        .WithMany("EstimateLaborCosts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Estimate", "Estimation")
                        .WithMany("LaborCosts")
                        .HasForeignKey("EstimateLaborCostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Estimation");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Invoice", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.ProjectMilestone", "Milestone")
                        .WithMany("Invoices")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.PaymentType", "PaymentType")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Project", "Project")
                        .WithMany("Invoices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("InvoiceStatus");

                    b.Navigation("Milestone");

                    b.Navigation("PaymentType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.InvoiceAuditLog", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionType");

                    b.Navigation("EntityType");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentReceipt", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Invoice", "Invoice")
                        .WithMany("PaymentReceipts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.PaymentMode", "PaymentMode")
                        .WithMany("PaymentReceipts")
                        .HasForeignKey("PaymentModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMode");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Project", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "CreatedByUser")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "ProjectManager")
                        .WithMany("ManagedProjects")
                        .HasForeignKey("ProjectManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "UpdatedByUser")
                        .WithMany("UpdatedProjects")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ProjectManager");

                    b.Navigation("ProjectStatus");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectAuditLog", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActionType");

                    b.Navigation("EntityType");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectMilestone", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.MilestoneStatus", "MilestoneStatus")
                        .WithMany("Milestones")
                        .HasForeignKey("MilestoneStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MilestoneStatus");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectTeamMember", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.User", "Employee")
                        .WithMany("ProjectTeamMembers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Role", "Roles")
                        .WithMany("TeamMembers")
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.TeamRole", null)
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamRoleId");

                    b.Navigation("Employee");

                    b.Navigation("Project");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.User", b =>
                {
                    b.HasOne("GenXThofa.Technologies.Estimer.Data.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.CostType", b =>
                {
                    b.Navigation("AdditionalCosts");

                    b.Navigation("DirectCosts");

                    b.Navigation("IndirectCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Estimate", b =>
                {
                    b.Navigation("AdditionalCosts");

                    b.Navigation("DirectCosts");

                    b.Navigation("IndirectCosts");

                    b.Navigation("LaborCosts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.EstimationStatus", b =>
                {
                    b.Navigation("Estimates");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Invoice", b =>
                {
                    b.Navigation("PaymentReceipts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.MilestoneStatus", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentMode", b =>
                {
                    b.Navigation("PaymentReceipts");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.PaymentType", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Project", b =>
                {
                    b.Navigation("Estimates");

                    b.Navigation("Invoices");

                    b.Navigation("Milestones");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectMilestone", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.Role", b =>
                {
                    b.Navigation("TeamMembers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.TaxConfig", b =>
                {
                    b.Navigation("Estimates");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.TeamRole", b =>
                {
                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("GenXThofa.Technologies.Estimer.Data.Models.User", b =>
                {
                    b.Navigation("CreatedClients");

                    b.Navigation("CreatedProjects");

                    b.Navigation("EstimateLaborCosts");

                    b.Navigation("ManagedProjects");

                    b.Navigation("ProjectTeamMembers");

                    b.Navigation("UpdatedClients");

                    b.Navigation("UpdatedProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
